export const BOOKS = [
    {
        name: 'Позже',
        autor: 'Кинг С.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '300',
        picture: 'https://img-gorod.ru/28/594/2859479_preview.jpg',
        count: 0,
        genre: 'Художественная литература',
        category: 'fiction',
        date: '01.05.2020',
        art:'A55',
        inBasket: false,
        id: 101
    },
    {
        name: 'Девы',
        autor: 'Михаэлидес А.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '499',
        picture: 'https://img-gorod.ru/28/582/2858220_preview.jpg',
        count: 0,
        genre: 'Художественная литература',
        category: 'fiction',
        date: '01.11.2020',
        art:'A55',
        inBasket: false,
        id: 102
    },
    {
        name: 'Invent and Wander. Избранные статьи',
        autor: 'Айзексон У.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '299',
        picture: 'https://img-gorod.ru/28/641/2864109_preview.jpg',
        count: 2,
        genre: 'Деловая литература',
        category: 'business',
        date: '01.03.2020',
        art:'A55',
        inBasket: false,
        id: 103
    },
    {
        name: 'Эмоциональный мозг',
        autor: 'Симонов П.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '799',
        picture: 'https://img-gorod.ru/28/629/2862952_preview.jpg',
        count: 6,
        genre: 'Психология',
        category: 'psychology',
        date: '01.08.2020',
        art:'C55',
        inBasket: false,
        id: 104
    },
    {
        name: 'Львиное сердце',
        autor: 'Акимова А.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '199',
        picture: 'https://img-gorod.ru/28/642/2864281_preview.jpg',
        count: 4,
        genre: 'Художественная литература',
        category: 'fiction',
        date: '06.05.2020',
        art:'B55',
        inBasket: false,
        id: 105
    },
    {
        name: 'Убийца по вызову',
        autor: 'Леонов Н., Макеев А.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '187',
        picture: 'https://img-gorod.ru/28/741/2874172_detail.jpg',
        count: 4,
        category: 'fiction',
        date: '06.05.2020',
        art:'O55',
        inBasket: false,
        id: 106
    },
    {
        name: 'Смерть по-соседски',
        autor: 'Мамоев Г.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '199',
        picture: 'https://img-gorod.ru/28/741/2874174_detail.jpg',
        count: 4,
        genre: 'Художественная литература',
        category: 'fiction',
        date: '06.05.2020',
        art:'B55',
        inBasket: false,
        id: 107
    },
    {
        name: 'Бухгалтерский финансовый учет. Учебное пособие',
        autor: 'Бахолдина И.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '1176',
        picture: 'https://img-gorod.ru/28/708/2870826_detail.jpg',
        count: 4,
        category: 'business',
        date: '06.05.2020',
        art:'C55',
        inBasket: false,
        id: 108
    },
    {
        name: 'В точке покоя. Воркбук для самопознания, поиска ресурса и вдохновения',
        autor: 'Примаченко О.',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        price: '487',
        picture: 'https://img-gorod.ru/28/746/2874664_detail.jpg',
        count: 4,
        genre: 'Художественная литература',
        category: 'psychology',
        date: '06.05.2020',
        art:'B55',
        inBasket: false,
        id: 109
    },
];